name: Setup Python with uv
description: Set up Python environment using uv package manager with caching

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.12'
  install-extras:
    description: 'Whether to install all extras with dependencies'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.install-extras }}" = "true" ]; then
          uv sync --group dev --all-extras
        else
          uv sync --group dev
        fi

