name: Setup Python with uv
description: Set up Python environment using uv package manager

inputs:
  install-extras:
    description: 'Whether to install all extras with dependencies'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      shell: bash
      run: uv python install 3.12

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.install-extras }}" = "true" ]; then
          uv sync --group dev --all-extras
        else
          uv sync --group dev
        fi
