name: Mypy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-uv

      - name: Run Mypy
        run: uv run mypy src/
